"""Realtime transcription resource (handwritten; not generated by Stainless).

Thin shim following the files/fine_tuning precedent: all logic lives in
`together.lib.realtime` so it survives OpenAPI regeneration.
"""

from __future__ import annotations

import threading
from typing import Any, Mapping, Callable, Optional

from .._resource import SyncAPIResource, AsyncAPIResource
from ..lib.realtime._state import BufferPool
from ..lib.realtime._types import (
    DEFAULT_AUDIO_FORMAT,
    BufferOptions,
    ReconnectOptions,
    TurnDetectionParam,
    RealtimeSessionEvent,
)
from ..lib.realtime._session import (
    RealtimeTranscriptionSession,
    AsyncRealtimeTranscriptionSession,
)
from ..lib.realtime._connection import (
    RealtimeConnectionManager,
    AsyncRealtimeConnectionManager,
)

__all__ = ["RealtimeResource", "AsyncRealtimeResource"]


class RealtimeResource(SyncAPIResource):
    """`client.realtime` — realtime transcription over WebSocket (sync)."""

    _pool: Optional[BufferPool] = None
    _pool_lock = threading.Lock()

    @property
    def buffer_pool(self) -> BufferPool:
        """Client-scoped recovery-buffer pool shared by this client's sessions."""
        if self._pool is None:
            with self._pool_lock:
                if self._pool is None:
                    self._pool = BufferPool()
        return self._pool

    def connect(
        self,
        *,
        model: str,
        input_audio_format: str = DEFAULT_AUDIO_FORMAT,
        turn_detection: Optional[TurnDetectionParam] = None,
        language: Optional[str] = None,
        prompt: Optional[str] = None,
        rolling_prompt: Optional[bool] = None,
        energy_gate_rms: Optional[float] = None,
        session_params: Optional[Mapping[str, Any]] = None,
        extra_query: Optional[Mapping[str, Any]] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> RealtimeConnectionManager:
        """Advanced: open a raw typed realtime connection with no retry logic.

        Most callers should use `transcription()` instead, which adds
        automatic reconnection with audio replay.
        """
        return RealtimeConnectionManager(
            client=self._client,
            model=model,
            input_audio_format=input_audio_format,
            turn_detection=turn_detection,
            language=language,
            prompt=prompt,
            rolling_prompt=rolling_prompt,
            energy_gate_rms=energy_gate_rms,
            session_params=session_params,
            extra_query=extra_query,
            extra_headers=extra_headers,
        )

    def transcription(
        self,
        *,
        model: str,
        input_audio_format: str = DEFAULT_AUDIO_FORMAT,
        sample_rate: Optional[int] = None,
        language: Optional[str] = None,
        prompt: Optional[str] = None,
        rolling_prompt: Optional[bool] = None,
        energy_gate_rms: Optional[float] = None,
        session_params: Optional[Mapping[str, Any]] = None,
        turn_detection: Optional[TurnDetectionParam] = None,
        reconnect: Optional[ReconnectOptions] = None,
        buffer: Optional[BufferOptions] = None,
        keepalive_silence: bool = False,
        reprime_prompt: bool = False,
        max_chunk_ms: float = 1000.0,
        event_callback: Optional[Callable[[RealtimeSessionEvent], None]] = None,
        extra_query: Optional[Mapping[str, Any]] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> RealtimeTranscriptionSession:
        """Recommended: an auto-reconnecting realtime transcription session.

        Runs on a background event-loop thread (one per session) — intended
        for low session counts; use the async client for high concurrency.
        """
        return RealtimeTranscriptionSession(
            client=self._client,
            model=model,
            input_audio_format=input_audio_format,
            sample_rate=sample_rate,
            language=language,
            prompt=prompt,
            rolling_prompt=rolling_prompt,
            energy_gate_rms=energy_gate_rms,
            session_params=session_params,
            turn_detection=turn_detection,
            reconnect=reconnect,
            buffer=buffer,
            keepalive_silence=keepalive_silence,
            reprime_prompt=reprime_prompt,
            max_chunk_ms=max_chunk_ms,
            pool=self.buffer_pool,
            event_callback=event_callback,
            extra_query=extra_query,
            extra_headers=extra_headers,
        )


class AsyncRealtimeResource(AsyncAPIResource):
    """`client.realtime` — realtime transcription over WebSocket (async)."""

    _pool: Optional[BufferPool] = None
    _pool_lock = threading.Lock()

    @property
    def buffer_pool(self) -> BufferPool:
        if self._pool is None:
            with self._pool_lock:
                if self._pool is None:
                    self._pool = BufferPool()
        return self._pool

    def connect(
        self,
        *,
        model: str,
        input_audio_format: str = DEFAULT_AUDIO_FORMAT,
        turn_detection: Optional[TurnDetectionParam] = None,
        language: Optional[str] = None,
        prompt: Optional[str] = None,
        rolling_prompt: Optional[bool] = None,
        energy_gate_rms: Optional[float] = None,
        session_params: Optional[Mapping[str, Any]] = None,
        extra_query: Optional[Mapping[str, Any]] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> AsyncRealtimeConnectionManager:
        """Advanced: open a raw typed realtime connection with no retry logic."""
        return AsyncRealtimeConnectionManager(
            client=self._client,
            model=model,
            input_audio_format=input_audio_format,
            turn_detection=turn_detection,
            language=language,
            prompt=prompt,
            rolling_prompt=rolling_prompt,
            energy_gate_rms=energy_gate_rms,
            session_params=session_params,
            extra_query=extra_query,
            extra_headers=extra_headers,
        )

    def transcription(
        self,
        *,
        model: str,
        input_audio_format: str = DEFAULT_AUDIO_FORMAT,
        sample_rate: Optional[int] = None,
        language: Optional[str] = None,
        prompt: Optional[str] = None,
        rolling_prompt: Optional[bool] = None,
        energy_gate_rms: Optional[float] = None,
        session_params: Optional[Mapping[str, Any]] = None,
        turn_detection: Optional[TurnDetectionParam] = None,
        reconnect: Optional[ReconnectOptions] = None,
        buffer: Optional[BufferOptions] = None,
        keepalive_silence: bool = False,
        reprime_prompt: bool = False,
        max_chunk_ms: float = 1000.0,
        event_callback: Optional[Callable[[RealtimeSessionEvent], None]] = None,
        extra_query: Optional[Mapping[str, Any]] = None,
        extra_headers: Optional[Mapping[str, str]] = None,
    ) -> AsyncRealtimeTranscriptionSession:
        """Recommended: an auto-reconnecting realtime transcription session."""
        return AsyncRealtimeTranscriptionSession(
            client=self._client,
            model=model,
            input_audio_format=input_audio_format,
            sample_rate=sample_rate,
            language=language,
            prompt=prompt,
            rolling_prompt=rolling_prompt,
            energy_gate_rms=energy_gate_rms,
            session_params=session_params,
            turn_detection=turn_detection,
            reconnect=reconnect,
            buffer=buffer,
            keepalive_silence=keepalive_silence,
            reprime_prompt=reprime_prompt,
            max_chunk_ms=max_chunk_ms,
            pool=self.buffer_pool,
            event_callback=event_callback,
            extra_query=extra_query,
            extra_headers=extra_headers,
        )
