# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing_extensions import Literal, TypeAlias

__all__ = ["OperationErrorCode"]

OperationErrorCode: TypeAlias = Literal[
    "TRAINING_OPERATION_ERROR_CODE_UNSPECIFIED",
    "TRAINING_OPERATION_ERROR_CODE_RESOURCE_EXHAUSTED",
    "TRAINING_OPERATION_ERROR_CODE_TIMEOUT",
    "TRAINING_OPERATION_ERROR_CODE_INTERNAL_ERROR",
    "TRAINING_OPERATION_ERROR_CODE_SESSION_NOT_ACTIVE",
    "TRAINING_OPERATION_ERROR_CODE_INVALID_INPUT",
    "TRAINING_OPERATION_ERROR_CODE_NON_FINITE_LOSS",
]
